### ISSUE TITLE
制作保存kernel image的硬盘镜像

### ISSUE THREAD

**Issue by ssdemajia** [ruier/VxWorks_image_for_qemu#2]
我是使用软盘来作为kernel image（vxWorks这个文件）的载体，但是vxworks的大小很容易就会超过1.4m，想问问作者的hda.img是怎么制作的？我看这个文件也被写入bootrom，同时vxWorks也被写入，谢谢。

**Comment by ruier** [comment]
我是使用了一款专门制作软盘的工具，是 Windows 上的，但是年代太久远。我忘记叫啥名了。

**Comment by ssdemajia** [comment]
谢谢，我现在用vmware也行了
